### ISSUE TITLE
Configurations

### ISSUE THREAD

**Issue by XietrZ** [deib-polimi/WiDiSi#1]
Sir Nasser,

Can you please give summarize or descirptions on what you are trying to do in your configurations? It would be a great help sir.

**Comment by XietrZ** [comment]
I apologize I haven't explained it enough. What I am trying to say is that write in your configurations on what would be your expected output creating that specific  configuration. Because I have observed that when i was running all you configurations, I can't tell what are the differences among them.

**Comment by nasser1941** [comment]
For clarity I am going to remove those configuration and applications that are not related to the main functionality of the project. Then I would add some comments on the configuration file so that you understand it line by line.

**Comment by XietrZ** [comment]
Ok sir, Looking forward to it.
